### ISSUE TITLE
ViewPager don't show last item

### ISSUE THREAD

**Issue by hai199580** [siralam/LoopingViewPager#24]
I have a list of fragment, and i want to bind to my ViewPager, but in last page, it not show my fragment :'(

Here is my Pager Adapter

![image](https://user-images.githubusercontent.com/31401366/65868706-fcfa9b00-e3a2-11e9-9455-a31a2f148190.png)

and item_infinity_pager.xml

`<?xml version="1.0" encoding="utf-8"?>`
`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"`
           `  android:id="@+id/flContainer"`
          `   android:layout_width="match_parent"`
          `   android:layout_height="match_parent">`
`</FrameLayout>`

**Comment by siralam** [comment]
Hm, I am not very sure if fragment is really supported. But I do see a problem in your code here -

You are using `listPosition+1` as the id of the frameLayout. The last item of the list is used twice in the view pager to create the looping effect, so probably there are 2 FrameLayouts with the same id (listPosition of the last item). So probably the fragment is replaced to the hidden one but not the one shown. 

Try other ways to assign ID instead of using list Position to see if that solves your problem.
